{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "spooknix.fullname" . }}
  labels:
    app: {{ include "spooknix.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "spooknix.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: spooknix_active_sessions
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.targetActiveSessionsAvgValue }}
{{- end }}
