name: Nix Fmt

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-fmt:
    uses: VoidNxSEC/voidnxlabs-workflows/.github/workflows/reusable-nix-fmt.yml@main
    secrets: inherit

